name: vibe_portfolio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^14.0.0 # or latest version
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.3.2
  illusionary_vibe:
    path: ../../illusionary_vibe
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

